use_frameworks!

target 'Weather' do
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Alamofire'
  pod 'pop'
  pod 'ObjectMapper'
  pod 'MBProgressHUD'
  pod 'TZImagePickerController'
end
