use_frameworks!

target 'Weather'

pod 'Moya/RxSwift'
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'
pod 'Alamofire'
pod 'pop'
pod "Moya-SwiftyJSONMapper/RxSwift"
pod 'MBProgressHUD'
pod 'TZImagePickerController'
